# Generated by Django 3.0.7 on 2020-06-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200625_1451'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uczestnik',
            new_name='Participant',
        ),
    ]
