# Generated by Django 3.0.7 on 2020-07-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20200625_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='lastname',
            field=models.CharField(default='null', max_length=32),
            preserve_default=False,
        ),
    ]
