# Generated by Django 3.0.7 on 2020-07-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_participant_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='groupname',
            field=models.CharField(default='null', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='year',
            field=models.IntegerField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
