# Generated by Django 3.0.7 on 2020-07-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20200705_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='year',
            field=models.IntegerField(),
        ),
    ]
